### ISSUE TITLE
[Question] Happy to showcase?

### ISSUE THREAD

**Issue by Sammyjo20** [kilianweisl/hellocash-php-sdk#1]
Hey 👋 thank you for using Saloon to build this SDK, I saw it through the dependants list and I thought I’d check it out. The way you have built it looks really nice, and really well thought out!

I really liked the tests you wrote too with fixtures, and the error handling. 

I’d love to showcase it on the docs in the “Showcase” section, would you be okay with that?

**Comment by kilianweisl** [comment]
Hey! Thanks for building Saloon, I really love working with it! :) 

Also, thank you for the nice feedback! There are definitely some things that need some improvements. However, I'd really appreciate being in the Showcase section!

**Comment by Sammyjo20** [comment]
Fantastic, I will get it added to the docs, and many thanks for the feedback! So glad it's adding value.

Have a great day!
